version: '3'
services:
  flask_app_1:
    image: flask-agent:latest
    environment:
      - AGENT_NAME=agent_1

  flask_app_2:
    image: flask-agent:latest
    environment:
      - AGENT_NAME=agent_2

  flask_app_3:
    image: flask-agent:latest
    environment:
      - AGENT_NAME=agent_3

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
